from fastapi import APIRouter, Depends
from typing import List
from ..auth import get_current_user
from ..db import get_db_collection

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("")
def get_reports_data(current_user: dict = Depends(get_current_user)):
    inst_coll = get_db_collection("institutions")
    proposals_coll = get_db_collection("proposals")
    meetings_coll = get_db_collection("meetings")
    users_coll = get_db_collection("users")
    
    institutions = list(inst_coll.find())
    proposals = list(proposals_coll.find())
    meetings = list(meetings_coll.find())
    users = list(users_coll.find())
    
    total_inst = len(institutions)
    
    # 1. Lead Conversion Report
    pipeline_stages = ["New Lead", "Contacted", "Meeting Scheduled", "Proposal Sent", "Negotiation", "Closed Won", "Closed Lost"]
    conversion_stages = []
    for stage in pipeline_stages:
        count = sum(1 for inst in institutions if inst.get("lead_status") == stage)
        percentage = (count / total_inst * 100) if total_inst > 0 else 0
        conversion_stages.append({
            "stage": stage,
            "count": count,
            "percentage": round(percentage, 1)
        })
        
    # Conversion Rate (Closed Won / Total Leads)
    closed_won_count = sum(1 for inst in institutions if inst.get("lead_status") == "Closed Won")
    closed_lost_count = sum(1 for inst in institutions if inst.get("lead_status") == "Closed Lost")
    total_closed = closed_won_count + closed_lost_count
    conversion_rate = (closed_won_count / total_closed * 100) if total_closed > 0 else (closed_won_count / total_inst * 100 if total_inst > 0 else 0)
    
    # 2. Sales Performance Report (by rep)
    # We find all unique sales reps emails from institutions, or pull from users collection
    sales_reps = list(set([inst.get("assigned_sales_executive") for inst in institutions if inst.get("assigned_sales_executive")]))
    if not sales_reps:
        # Fallback to users list or current user
        sales_reps = [u.get("email") for u in users if u.get("role") == "Sales Executive"]
        if not sales_reps:
            sales_reps = [current_user.get("email")]
            
    sales_performance = []
    for rep in sales_reps:
        rep_insts = [inst for inst in institutions if inst.get("assigned_sales_executive") == rep]
        rep_total = len(rep_insts)
        rep_won = sum(1 for inst in rep_insts if inst.get("lead_status") == "Closed Won")
        rep_active = sum(1 for inst in rep_insts if inst.get("lead_status") not in ["Closed Won", "Closed Lost"])
        
        # Calculate revenue generated by this rep (accepted proposals for institutions assigned to this rep)
        rep_inst_ids = [str(inst.get("_id")) for inst in rep_insts]
        rep_revenue = sum(
            p.get("proposal_amount", 0) 
            for p in proposals 
            if p.get("proposal_status") == "Accepted" and p.get("institution_id") in rep_inst_ids
        )
        
        # Get sales name
        rep_user = users_coll.find_one({"email": rep})
        rep_name = rep_user.get("name") if rep_user else rep.split("@")[0].title()
        
        sales_performance.append({
            "name": rep_name,
            "email": rep,
            "total_leads": rep_total,
            "closed_won": rep_won,
            "active_leads": rep_active,
            "revenue": rep_revenue
        })
        
    # 3. Meeting Report
    total_meetings = len(meetings)
    scheduled_meetings = sum(1 for m in meetings if m.get("status") == "Scheduled")
    completed_meetings = sum(1 for m in meetings if m.get("status") == "Completed")
    cancelled_meetings = sum(1 for m in meetings if m.get("status") == "Cancelled")
    
    # 4. Proposal Report
    total_proposals = len(proposals)
    draft_proposals = sum(1 for p in proposals if p.get("proposal_status") == "Draft")
    sent_proposals = sum(1 for p in proposals if p.get("proposal_status") == "Sent")
    accepted_proposals = sum(1 for p in proposals if p.get("proposal_status") == "Accepted")
    rejected_proposals = sum(1 for p in proposals if p.get("proposal_status") == "Rejected")
    
    total_value = sum(p.get("proposal_amount", 0) for p in proposals)
    accepted_value = sum(p.get("proposal_amount", 0) for p in proposals if p.get("proposal_status") == "Accepted")
    avg_proposal_amount = (total_value / total_proposals) if total_proposals > 0 else 0
    
    return {
        "conversion_rate": round(conversion_rate, 1),
        "lead_conversion": conversion_stages,
        "sales_performance": sales_performance,
        "meetings": {
            "total": total_meetings,
            "scheduled": scheduled_meetings,
            "completed": completed_meetings,
            "cancelled": cancelled_meetings
        },
        "proposals": {
            "total": total_proposals,
            "draft": draft_proposals,
            "sent": sent_proposals,
            "accepted": accepted_proposals,
            "rejected": rejected_proposals,
            "total_value": total_value,
            "accepted_value": accepted_value,
            "avg_amount": round(avg_proposal_amount, 2)
        }
    }
